
import { GoogleGenAI } from '@google/genai';
import Order from '../models/Order.js';

/**
 * @desc    Generate a logistical intelligence report for system operators
 * @access  Private/Admin
 */
export const generateOrderReport = async (req, res) => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    // Fetch orders for context
    const orders = await Order.find({}).limit(20).populate('user', 'name');
    
    const prompt = `
      System Context: Professional Enterprise Logistics System.
      Goal: Provide a high-level logistical report for the dispatch and fulfillment team.
      Data to analyze: ${JSON.stringify(orders)}
      
      Instructions for output:
      1. Use formal business language.
      2. Summarize current order volume and status distribution.
      3. Identify logistical bottlenecks or risks in the urban delivery network.
      4. Suggest optimizations for delivery efficiency and route planning.
      5. Write as if generated by the "In-N-Out Intelligence Module".
      
      Format: Professional text with clear section headers.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: [{ parts: [{ text: prompt }] }],
    });

    res.status(200).json({ report: response.text });
  } catch (error) {
    console.error('System Logic Error:', error);
    res.status(500).json({ message: 'Logistics Intelligence Module Unavailable', error: error.message });
  }
};
