
import { GoogleGenAI } from '@google/genai';
import Order from '../models/Order.js';

/**
 * @desc    Generate a logistical intelligence report for university admins
 * @access  Private/Admin
 */
export const generateOrderReport = async (req, res) => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    // Fetch orders for context
    const orders = await Order.find({}).limit(20).populate('user', 'name');
    
    const prompt = `
      System Context: Professional Logistics System developed for Admas University CS Department.
      Goal: Provide a high-level logistical report for the dispatch team.
      Data to analyze: ${JSON.stringify(orders)}
      
      Instructions for output:
      1. Use formal academic language.
      2. Summarize current order volume and status distribution (Pending vs Approved).
      3. Identify logistical bottlenecks or risks.
      4. Suggest optimizations for the delivery routes in Addis Ababa.
      5. DO NOT mention any AI brands or external services. Write as if generated by the "Admas System Intelligence Module".
      
      Format: Professional text with section headers.
    `;

    const result = await ai.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: [{ parts: [{ text: prompt }] }],
    });

    res.status(200).json({ report: result.text });
  } catch (error) {
    console.error('System Logic Error:', error);
    res.status(500).json({ message: 'Logistics Intelligence Module Unavailable', error: error.message });
  }
};
